# -*- coding: utf-8 -*-
{
    'name': "PPTS Stryker Survey Via E-Mail and Whatsapp",
    'summary': """
        Sending Survey for the customers in Parent and child ticket through Emails, Whatsapp and creating service request if fails customer rating""",
    'description': """This technical module which sends a survey link to customer via E-mail, WhatsApp based on given configurations and customizations done in Survey, Survey Participants.etc""",
    'category': 'Survey',
    'version': '1.0',
    'installable': True,
    'license': 'OEEL-1',
    'depends': ['base', 'survey', 'ppts_parent_ticket', 'ppts_service_request','hr', 'ppts_custom_workflow','watsapp_sms'],
    'data': [
        'data/sr_escalation_cron.xml',
        # 'security/groups.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/mail_template_data.xml',
        'data/survey_cron.xml',
        'data/import_sr_creation_cron.xml',
        'data/survey_followup_cron.xml',
        'views/res_config_settings_view.xml',
        'views/inherit_views.xml',
        'views/survey_views.xml',
        'views/res_partner_view.xml',
        'views/service_request_sr_survey_views.xml',
        'views/hr_employee_views.xml',
        'views/survey_templates.xml',
        'views/stock_production_lot_view.xml',
        'views/followup_history_views.xml',
        'views/blast_survey_views.xml',
        'views/blast_survey_views_history.xml',
        # 'views/ir_cron_views.xml',
        'wizard/fill_survey_view.xml',
        'wizard/reopen_ticket_views.xml',
        'wizard/blast_survey_popup_views.xml',
        'wizard/survey_invite_views.xml',
        'wizard/question_wise_report_view.xml'
    ],
}
